LogIn with 3 errors
Still has error
FATAL EXCEPTION: main (Ask Gemini)
                                                                                                    Process: com.example.viamm, PID: 19748
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.viamm/com.example.viamm.LoginActivity}: android.view.InflateException: Binary XML file line #11 in com.example.viamm:layout/activity_login: Binary XML file line #11 in com.example.viamm:layout/activity_login: Error inflating class android.widget.RelativeLayout

Caused by: android.view.InflateException: Binary XML file line #11 in com.example.viamm:layout/activity_login: Binary XML file line #11 in com.example.viamm:layout/activity_login: Error inflating class android.widget.RelativeLayout
                                                                                                    Caused by: android.view.InflateException: Binary XML file line #11 in com.example.viamm:layout/activity_login: Error inflating class android.widget.RelativeLayout
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException

Caused by: android.content.res.Resources$NotFoundException: Drawable com.example.viamm:color/material_dynamic_neutral99 with resource ID #0x7f050210
                                                                                                    Caused by: android.content.res.Resources$NotFoundException: Resource "com.example.viamm:color/material_dynamic_neutral99" (7f050210) is not a Drawable (color or path): TypedValue{t=0x1/d=0x7f050210 a=-1 r=0x7f050210}